language: ruby
rvm:
  - "2.3.1"
script: TESTOPTS="--verbose" bundle exec rake test
addons:
notifications:
  email: false
  irc: "chat.freenode.net#galacticaactual"
  slack: galacticaactual:rhAXgZ68aoikbxBBA05xIUVC
