production:
  clients:
    default:
      database: SteemData
      hosts:
        - mongo1.steemdata.com:27017
      options:
        user: 'steemit'
        password: 'steemit'
development:
  clients:
    default:
      database: SteemData
      hosts:
        - mongo1.steemdata.com:27017
      options:
        user: 'steemit'
        password: 'steemit'
test:
  clients:
    default:
      database: SteemData
      hosts:
        - mongo1.steemdata.com:27017
      options:
        user: 'steemit'
        password: 'steemit'

