# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c5496e1f6dc0486465bfdd3e0aae45e53ac2a9cb0d3c9d39a7f627d30943c0c6121b387678ace0fb317a7244b0d6905e4268890565d0289adfaf18cd56c3b54

test:
  secret_key_base: 87d6f6e8f55f33006e614d5baef201ace3376eb53324daa4749339d43f5097f4c1fb7de03dd56281e05f4d9f78aaf6b79f53d19013cb96a2e4b3a2e69f750d55

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
